eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 1213
spring:
  application:
    name: service-api-consumer
feign:
  hystrix:
    enabled: true
